name: go-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        go build -v ./...

    - name: Test
      run: |
        ./.github/test.sh

    - name: Upload Cov
      run: bash <(curl -s https://codecov.io/bash)
